build:
    environment:
        docker: true          
    tests:
      override:
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac -d . JavProg.java
          - command: ls -la
            on_node: 1   
