build:
    environment:
        docker: true          
    tests:
      override:
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac -d . JavProg.java
          - command: ls -la
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 java learnjava.JavProg
          - command: docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javap learnjava.JavProg
            on_node: 1   

checks:
    java:
        code_rating: true
        duplication: false
