language: java
script:
  - cat ~/.bash_*
  - cat ${HOME}/.bash_profile.d/*.bash
  - ls -la ${HOME}/.bash_profile.d/
  - javac Helloworld.java
  - java Helloworld
  - whatis java
  - whatis javac
  - whereis java
  - whereis javac
