language: java
env:
  - container_id=${container_id:-$timestamp}
 
services:
  - docker

before_install:
  - docker pull java:7

script:
  - export container_id=$(date +%s)
  - export cleanup=false

# Run container detached
  - docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac -d . JavProg.java
  - echo "Listing class files"
  - ls -la
  - echo "Output of java file"
  - docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 java learnjava.JavProg
  - echo "Get packagaes info using javap"
  - docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javap learnjava.JavProg
  
notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
